# Generated by Django 5.0.1 on 2024-01-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
    ]
