# Generated by Django 5.0.1 on 2024-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_authormodel_options_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
