# Generated by Django 5.0.1 on 2024-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
